url: http://winton-ubuntu.local:9395
site: test
categories:
  - name: Category
    tests: 
    - id: 1
      name: Test
      variants: 
      - id: 2
        name: v1
      - id: 3
        name: v2
      - id: 4
        name: v3