#!/usr/bin/env ruby

r = %w(require application sinatra active_wrapper model).collect do |file|
  '-r ' + File.expand_path("#{File.dirname(__FILE__)}/../lib/a_b/boot/#{file}")
end

exec "irb #{r.join(' ')}"