#!/usr/bin/env ruby

require 'fileutils'
require File.expand_path('../../lib/a_b_server/gems', __FILE__)

ABServer::Gems.require(:dj)

require 'with_pid'

puts with_pid(
  :action => ARGV[0] || 'start', # start or stop
  :command => File.expand_path(File.dirname(__FILE__)) + "/runner 'Delayed::Worker.new.start'",
  :environment => ARGV[2] || 'development',
  :name => "dj",
  :pid => "/tmp/delayed_job.a_b_server.#{ARGV[1] || 0}.pid",
  :tmp => "/tmp"
)