#!/usr/bin/env ruby

require 'fileutils'
require File.expand_path('../../lib/a_b/gems', __FILE__)

AB::Gems.require(:dj)

require 'with_pid'

puts with_pid(
  :action => ARGV[0], # start or stop
  :command => File.expand_path(File.dirname(__FILE__)) + "/runner 'Delayed::Worker.new.start'",
  :name => "dj",
  :pid => "/tmp/delayed_job.a_b.#{ARGV[1]}.pid",
  :tmp => "/tmp"
)