--- 
tests: 
- name: Test
  id: 63
  variants: 
  - name: v1
    id: 187
    visits: 0
  - name: v2
    id: 188
    visits: 0
  - name: v3
    id: 189
    visits: 0
- name: Test 2
  id: 64
  variants: 
  - name: v4
    id: 190
    visits: 0
  - name: v5
    id: 191
    visits: 0
  - name: v6
    id: 192
    visits: 0
