--- 
tests: 
- name: Test
  id: 47
  variants: 
  - name: v1
    id: 139
    visits: 0
  - name: v2
    id: 140
    visits: 0
  - name: v3
    id: 141
    visits: 0
- name: Test 2
  id: 48
  variants: 
  - name: v4
    id: 142
    visits: 0
  - name: v5
    id: 143
    visits: 0
  - name: v6
    id: 144
    visits: 0
